### ISSUE TITLE
how to get a token representation from KALA

### ISSUE THREAD

**Issue by pavaris-pm** [Nardien/KALA#3]
I want to ask that where can i get a _**token representation**_ from KALA for my analysis of seen and unseen entites which is similar to what you analyze in the paper, but i have no idea of how and where to get it from KALA. Can you please give me a guidance to do it ?

**Comment by Nardien** [comment]
Hi. Thank you for your interest in our work!

For a token representation from KALA in visualizations, we use the hidden states from the last layer of BERT.

You can use `sequence_output` for your analysis of seen and unseen entities.

Please refer to this code:
https://github.com/Nardien/KALA/blob/3d44db8926fcabea982a886a8cb058d8ba91957b/models/KALA/modeling_bert.py#L67

**Comment by pavaris-pm** [comment]
Thanks for a very quick reply ! , here i have another question, 

1. suppose that i use just only an entity memory without leveraging of knowledge graph at first , will token representation of _**KALA (point-wise)**_ will different from the ordinary pre-trained BERT model ? if it is different, can you please clarify me more about the ability of _**Entity Memory without KG**_ that makes it works better than ordinary BERT.
2. In `construct.py` you use the trained model to do both relation extraction and entity embedding, my question is that do we need to use an individual model to do both task ? can we use different model to do each task such as using model A for relation Extraction and Model B for entity embedding ? will it make any significant result ?

Thank you in advance

**Comment by Nardien** [comment]
Sorry for the delay in my response and thank you for your understanding.
Here are the answers to your questions:

1. Regarding the token representation, the answer is "yes". The token representation of KALA (point-wise) differs from the ordinary BERT because KALA (point-wise) also modulates the hidden representations of each entity conditioned on the entity embedding stored in the entity memory. (See Eq 1 and 2 in the main paper)
Even without a KG, KALA applies the "same feature modulation" to tokens that correspond to the same entity. For example, in Figure 1, the tokens "New" and "York" are modulated by the same gammas and betas since they correspond to the entity "New York". Therefore, this approach can help BERT better recognize entities that span multiple tokens and can potentially improve performance in the given task. We have also included a relevant case study in Section 5.5 of the main paper.

2. You can use the different models for relation extraction and entity embedding. It might be a good choice to utilize a clinical-specific BERT model, such as PubMedBERT, for entity embedding in order to achieve better results.

**Comment by pavaris-pm** [comment]
That was clear for what i asked for. Thank you so much.
